services:

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQLUSER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLPASSWORD}
